DROP DATABASE node_aula;
CREATE DATABASE IF NOT EXISTS node_aula;
USE node_aula;

CREATE TABLE tb_usuario (
	id INT PRIMARY KEY AUTO_INCREMENT NOT NULL,
    nome VARCHAR(30) NOT NULL,
    email VARCHAR(70) NOT NULL,
    senha VARCHAR(40) NOT NULL
);

